=== ClearElection/info-site/data/election_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Election",
  "description": "ClearElection Election definition, v0.0",
  "type": "object",
  "properties": {
    "version": { "enum": ["0.0"] },
    "name": { "type": "string" },
    "agents": {
      "type": "object",
      "properties": {
        "signin": { "$ref": "#/definitions/agent" },
        "booth": { "$ref": "#/definitions/agent" }
      }
    },
    "schedule": {
      "type": "object",
      "properties": {
        "pollsOpen": { "type": "string", "format": "date-time" },
        "pollsClose": { "type": "string", "format": "date-time" }
      }
    },
    "contests": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "contestId": { "type": "string" },
          "name": { "type": "string" },
          "ranked": { "type": "boolean", "default": false },
          "multiplicity": { "type": "integer", "default": 1, "minimum": 1 },
          "writeIn": { "type": "boolean", "default": false },
          "candidates": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "candidateId": { "type": "string" },
                "name": { "type": "string" }
              },
              "required": ["candidateId", "name"]
            }
          }
        },
        "required": ["contestId", "name", "candidates"]
      }
    }
  },
  "required": ["version", "name", "schedule", "contests"],
  "definitions": {
    "agent": {
      "type": "object",
      "properties": {
        "uri": { "type": "string", "format": "uri" }
      },
      "required": ["uri"]
    }
  }
}

=== ClearElection/info-site/data/sample_election.json
{
  "version": "0.0",
  "name": "Election Name-3",
  "agents": {
    "signin": {
      "uri": "http://agents.example.com/signin-3/"
    },
    "booth": {
      "uri": "http://agents.example.com/booth-3/"
    }
  },
  "schedule": {
    "pollsOpen": "2014-11-23T15:56:19+00:00",
    "pollsClose": "2015-01-22T15:56:19+00:00"
  },
  "contests": [
    {
      "contestId": "contestId-6",
      "name": "Contest Name-6",
      "ranked": true,
      "multiplicity": 3,
      "writeIn": true,
      "candidates": [
        {
          "candidateId": "candidateId-15",
          "name": "Candidate Name-15"
        },
        {
          "candidateId": "candidateId-16",
          "name": "Candidate Name-16"
        },
        {
          "candidateId": "candidateId-17",
          "name": "Candidate Name-17"
        }
      ]
    },
    {
      "contestId": "contestId-7",
      "name": "Contest Name-7",
      "ranked": false,
      "multiplicity": 1,
      "writeIn": false,
      "candidates": [
        {
          "candidateId": "candidateId-18",
          "name": "Candidate Name-18"
        },
        {
          "candidateId": "candidateId-19",
          "name": "Candidate Name-19"
        }
      ]
    }
  ]
}
